# Generated by Django 2.2.1 on 2019-05-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=30)),
                ('password', models.CharField(default='admin', max_length=30)),
                ('name', models.CharField(default='', max_length=50)),
                ('faculty', models.CharField(default='', max_length=256)),
                ('year_of_study', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1)),
            ],
        ),
    ]
