# Generated by Django 2.2.1 on 2019-05-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20190507_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('number_of_hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('student', models.ForeignKey(on_delete=True, related_name='subject', to='subject.Subject')),
                ('subject', models.ForeignKey(on_delete=True, related_name='student', to='accounts.Student')),
            ],
        ),
    ]
