# Generated by Django 2.2.1 on 2019-05-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester_number',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
