# Generated by Django 2.2.1 on 2019-05-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_semester_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_student',
            name='student',
            field=models.ForeignKey(on_delete=True, related_name='subject', to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='subject_student',
            name='subject',
            field=models.ForeignKey(on_delete=True, related_name='student', to='subject.Subject'),
        ),
    ]
